/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CarteiraRouteImport } from './routes/carteira'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as GruposRouteImport } from './routes/grupos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MercadoRouteImport } from './routes/mercado'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as QuestionarioRouteImport } from './routes/questionario'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as SmartInvestRouteImport } from './routes/smart-invest'
import { Route as AtivoTickerRouteImport } from './routes/ativo.$ticker'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteiraRoute = CarteiraRouteImport.update({
  id: '/carteira',
  path: '/carteira',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const GruposRoute = GruposRouteImport.update({
  id: '/grupos',
  path: '/grupos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MercadoRoute = MercadoRouteImport.update({
  id: '/mercado',
  path: '/mercado',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionarioRoute = QuestionarioRouteImport.update({
  id: '/questionario',
  path: '/questionario',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartInvestRoute = SmartInvestRouteImport.update({
  id: '/smart-invest',
  path: '/smart-invest',
  getParentRoute: () => rootRouteImport,
} as any)
const AtivoTickerRoute = AtivoTickerRouteImport.update({
  id: '/ativo/$ticker',
  path: '/ativo/$ticker',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carteira': typeof CarteiraRoute
  '/chat': typeof ChatRoute
  '/grupos': typeof GruposRoute
  '/login': typeof LoginRoute
  '/mercado': typeof MercadoRoute
  '/noticias': typeof NoticiasRoute
  '/questionario': typeof QuestionarioRoute
  '/ranking': typeof RankingRoute
  '/smart-invest': typeof SmartInvestRoute
  '/ativo/$ticker': typeof AtivoTickerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carteira': typeof CarteiraRoute
  '/chat': typeof ChatRoute
  '/grupos': typeof GruposRoute
  '/login': typeof LoginRoute
  '/mercado': typeof MercadoRoute
  '/noticias': typeof NoticiasRoute
  '/questionario': typeof QuestionarioRoute
  '/ranking': typeof RankingRoute
  '/smart-invest': typeof SmartInvestRoute
  '/ativo/$ticker': typeof AtivoTickerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carteira': typeof CarteiraRoute
  '/chat': typeof ChatRoute
  '/grupos': typeof GruposRoute
  '/login': typeof LoginRoute
  '/mercado': typeof MercadoRoute
  '/noticias': typeof NoticiasRoute
  '/questionario': typeof QuestionarioRoute
  '/ranking': typeof RankingRoute
  '/smart-invest': typeof SmartInvestRoute
  '/ativo/$ticker': typeof AtivoTickerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/carteira'
    | '/chat'
    | '/grupos'
    | '/login'
    | '/mercado'
    | '/noticias'
    | '/questionario'
    | '/ranking'
    | '/smart-invest'
    | '/ativo/$ticker'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carteira'
    | '/chat'
    | '/grupos'
    | '/login'
    | '/mercado'
    | '/noticias'
    | '/questionario'
    | '/ranking'
    | '/smart-invest'
    | '/ativo/$ticker'
  id:
    | '__root__'
    | '/'
    | '/carteira'
    | '/chat'
    | '/grupos'
    | '/login'
    | '/mercado'
    | '/noticias'
    | '/questionario'
    | '/ranking'
    | '/smart-invest'
    | '/ativo/$ticker'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarteiraRoute: typeof CarteiraRoute
  ChatRoute: typeof ChatRoute
  GruposRoute: typeof GruposRoute
  LoginRoute: typeof LoginRoute
  MercadoRoute: typeof MercadoRoute
  NoticiasRoute: typeof NoticiasRoute
  QuestionarioRoute: typeof QuestionarioRoute
  RankingRoute: typeof RankingRoute
  SmartInvestRoute: typeof SmartInvestRoute
  AtivoTickerRoute: typeof AtivoTickerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carteira': {
      id: '/carteira'
      path: '/carteira'
      fullPath: '/carteira'
      preLoaderRoute: typeof CarteiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grupos': {
      id: '/grupos'
      path: '/grupos'
      fullPath: '/grupos'
      preLoaderRoute: typeof GruposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercado': {
      id: '/mercado'
      path: '/mercado'
      fullPath: '/mercado'
      preLoaderRoute: typeof MercadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionario': {
      id: '/questionario'
      path: '/questionario'
      fullPath: '/questionario'
      preLoaderRoute: typeof QuestionarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-invest': {
      id: '/smart-invest'
      path: '/smart-invest'
      fullPath: '/smart-invest'
      preLoaderRoute: typeof SmartInvestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ativo/$ticker': {
      id: '/ativo/$ticker'
      path: '/ativo/$ticker'
      fullPath: '/ativo/$ticker'
      preLoaderRoute: typeof AtivoTickerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarteiraRoute: CarteiraRoute,
  ChatRoute: ChatRoute,
  GruposRoute: GruposRoute,
  LoginRoute: LoginRoute,
  MercadoRoute: MercadoRoute,
  NoticiasRoute: NoticiasRoute,
  QuestionarioRoute: QuestionarioRoute,
  RankingRoute: RankingRoute,
  SmartInvestRoute: SmartInvestRoute,
  AtivoTickerRoute: AtivoTickerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
